<?php

namespace AppBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getInvested()
    {
        $qb = $this->createQueryBuilder('tr');
        $qb->select('SUM(tr.amount)');
        $qb->where('cr.type = :type');

        $qb->setParameter('type', 100);

        return $qb->getQuery()->getArrayResult();
    }

    public function getTotalBalance()
    {
        
    }
}
