<?php

namespace AppBundle\Repository;

/**
 * UserWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWalletRepository extends \Doctrine\ORM\EntityRepository
{
}
