<?php

namespace AppBundle\Repository;

/**
 * WavesTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WavesTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
